development:
  adapter: postgresql
  encoding: unicode
  database: competitor_development
  pool: 5
  username: tomek
  password: tomek


test:
  adapter: postgresql
  encoding: unicode
  database: competitor_test
  pool: 5
  username: tomek
  password: tomek
